### PR TITLE
added checked option for uniform

### PR DESCRIPTION
**Pull request by vxsx**
This PR adds 'checked' option, adds class 'uniform-checked' when appropriate.
Useful for styling nearby elements based on checkbox/radio state.

### CODE REVIEW

**Comment by FinalAngel** [comment]
nice work :+1: LGTM you can merge and release. Don't forget to update the index.html page (demos)

**Comment by vxsx** [comment]
@FinalAngel would be amazing if you could rebuild "readthedocs" as I have no access there and it doesn't look like it's rebuilding automatically so far

**Comment by FinalAngel** [comment]
@vxsx can you create an account on readthedocs and let me here know the username? Will give you access than. Build is currently failing - dunno why.

**Comment by vxsx** [comment]
@FinalAngel fixed the build by changing some settings, kind of weird but it works now

**Comment by FinalAngel** [comment]
thank you @vxsx !!

**Pull request merged**
